export const ProductItems = [
  {
    id: 1,
    img: "https://w7.pngwing.com/pngs/197/951/png-transparent-sushi-chicken-chinese-noodles-wok-sushi-food-recipe-cuisine-thumbnail.png",
    title: "Вок с курицей",
    composition: "Соус терияки, курица, гречневая лапша, морковка по корейски",
    tag: ["острое"],
    cost: 250,
  },
  {
    id: 2,
    img: "https://w7.pngwing.com/pngs/678/694/png-transparent-frying-of-seafoods-wok-dish-tableware-recipe-frying-pan-cooking-wok-cook-map-cooking-wok-thumbnail.png",
    title: "Рамен с говядиной",
    composition: "Соус терияки, говядина, лапша пшеничная, болгарский перец",
    cost: 250,
  },
  {
    id: 4,
    img: "https://example.com/image1.jpg",
    title: "Вегетарианский суп",
    composition: "Лапша, овощи, томатный сок",
    tag: ["вегетарианское", "супы"],
    cost: 250,
  },
  {
    id: 5,
    img: "https://example.com/image2.jpg",
    title: "Бургер с курицей",
    composition: "Хлеб, курица, сыр, салат",
    tag: ["грибы", "мясо"],
    cost: 250,
  },
  {
    id: 6,
    img: "https://example.com/image3.jpg",
    title: "Паста с раками",
    composition: "Спагетти, раки, лимон, масло",
    tag: ["рыба", "морепродукты"],
    cost: 250,
  },
  {
    id: 7,
    img: "https://example.com/image4.jpg",
    title: "Салат с цыпленком",
    composition: "Цыпленок, овощи, соус ремoulade",
    tag: ["птица", "салаты"],
    cost: 250,
  },
  {
    id: 8,
    img: "https://example.com/image2.jpg",
    title: "Бургер с курицей",
    composition: "Хлеб, курица, сыр, салат",
    tag: ["грибы", "мясо"],
    cost: 250,
  },
  {
    id: 9,
    img: "https://example.com/image3.jpg",
    title: "Паста с раками",
    composition:
      "Спагетти, раки, лимон, масло,Спагетти, раки, лимон, масло,Спагетти, раки, лимон, масло,Спагетти, раки, лимон, масло",
    tag: ["рыба", "морепродукты"],
    cost: 250,
  },
  {
    id: 10,
    img: "https://example.com/image4.jpg",
    title: "Салат с цыпленком",
    composition: "Цыпленок, овощи, соус ремoulade",
    tag: ["птица", "салаты"],
    cost: 250,
  },
];
